In [19]:
import numpy as np
import pandas as pd

In [20]:
dataFrame = pd.read_csv("veriler.csv")
dataFrame

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [21]:
X = dataFrame.iloc[:,1:4]
Y = dataFrame.iloc[:,4]

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split( X, Y, test_size=0.33, random_state=0)

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

## Gaussian naive bayes

In [26]:
from sklearn.naive_bayes import GaussianNB

In [27]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)

pred = gnb.predict(x_test)
pred

array(['e', 'e', 'e', 'e', 'k', 'e', 'e', 'k'], dtype='<U1')

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
cm = confusion_matrix(y_test, pred)
cm

array([[0, 1],
       [6, 1]])

## Multinominal naive bayes

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

pred = mnb.predict(x_test)
pred

array(['e', 'e', 'e', 'e', 'e', 'e', 'e', 'e'], dtype='<U1')

In [32]:
cm = confusion_matrix(y_test, pred)
cm

array([[1, 0],
       [7, 0]])

## Bernoulli naive bayes

In [33]:
from sklearn.naive_bayes import BernoulliNB

In [34]:
bnb = BernoulliNB(force_alpha=True)
bnb.fit(x_train, y_train)

pred = bnb.predict(x_test)
pred

array(['e', 'e', 'e', 'e', 'e', 'e', 'e', 'e'], dtype='<U1')

In [35]:
cm = confusion_matrix(y_test, pred)
cm

array([[1, 0],
       [7, 0]])